/** Reference catalog of current powders from Vihtavuori, Reload Swiss, Lovex,
 *  Hodgdon, Alliant, Norma, and Vectan, offered as dropdown suggestions on
 *  the load form (in addition to whatever's already been typed into
 *  existing loads — see getDistinctLoadFieldValues). The field stays free
 *  text, so anything missing here (a newer/discontinued product, another
 *  brand) can still be typed in directly. */
export const POWDER_CATALOG: string[] = [
  // Vihtavuori N100 series (rifle)
  "Vihtavuori N110",
  "Vihtavuori N120",
  "Vihtavuori N130",
  "Vihtavuori N133",
  "Vihtavuori N135",
  "Vihtavuori N140",
  "Vihtavuori N150",
  "Vihtavuori N160",
  "Vihtavuori N165",
  "Vihtavuori N170",
  // Vihtavuori N300 series (pistol/shotgun)
  "Vihtavuori N105",
  "Vihtavuori N310",
  "Vihtavuori N320",
  "Vihtavuori N330",
  "Vihtavuori N340",
  "Vihtavuori N350",
  "Vihtavuori 3N37",
  "Vihtavuori 3N38",
  "Vihtavuori 20N29",
  "Vihtavuori 24N41",
  // Vihtavuori N500 series (high-energy rifle)
  "Vihtavuori N540",
  "Vihtavuori N550",
  "Vihtavuori N555",
  "Vihtavuori N560",
  "Vihtavuori N565",
  "Vihtavuori N568",
  "Vihtavuori N570",

  // Reload Swiss (pistol)
  "Reload Swiss RS12",
  "Reload Swiss RS14",
  "Reload Swiss RS20",
  "Reload Swiss RS24",
  "Reload Swiss RS30",
  // Reload Swiss (rifle)
  "Reload Swiss RS36",
  "Reload Swiss RS40",
  "Reload Swiss RS50",
  "Reload Swiss RS52",
  "Reload Swiss RS60",
  "Reload Swiss RS62",
  "Reload Swiss RS70",
  "Reload Swiss RS76",
  "Reload Swiss RS80",

  // Lovex D-series (double base, handgun + rifle)
  "Lovex D032",
  "Lovex D036",
  "Lovex D037.1",
  "Lovex D037.2",
  "Lovex D060",
  "Lovex D063",
  "Lovex D073.4",
  "Lovex D073.5",
  "Lovex D073.6",
  "Lovex D100",
  // Lovex S-series (single base, rifle)
  "Lovex S011",
  "Lovex S020",
  "Lovex S040",
  "Lovex S053",
  "Lovex S060",
  "Lovex S062",
  "Lovex S065",
  "Lovex S070",
  "Lovex S071",

  // Hodgdon (rifle)
  "Hodgdon H4198",
  "Hodgdon Benchmark",
  "Hodgdon H322",
  "Hodgdon Varget",
  "Hodgdon H4350",
  "Hodgdon H4831",
  "Hodgdon H4831SC",
  "Hodgdon H1000",
  "Hodgdon Retumbo",
  "Hodgdon US 869",
  "Hodgdon H50BMG",
  "Hodgdon BL-C(2)",
  "Hodgdon H335",
  "Hodgdon H380",
  "Hodgdon H414",
  "Hodgdon H110",
  "Hodgdon CFE 223",
  "Hodgdon CFE BLK",
  "Hodgdon Superformance",
  "Hodgdon LEVERevolution",
  // Hodgdon (pistol/shotgun)
  "Hodgdon Titegroup",
  "Hodgdon Titewad",
  "Hodgdon Clays",
  "Hodgdon International Clays",
  "Hodgdon Universal",
  "Hodgdon HP-38",
  "Hodgdon HS-6",
  "Hodgdon HS-7",
  "Hodgdon Longshot",
  "Hodgdon Trail Boss",
  "Hodgdon CFE Pistol",
  "Hodgdon Lil'Gun",

  // Alliant (rifle)
  "Alliant AR-Comp",
  "Alliant Power Pro 1200-R",
  "Alliant Power Pro 2000-MR",
  "Alliant Power Pro 4000-MR",
  "Alliant Power Pro Varmint",
  "Alliant Reloder 7",
  "Alliant Reloder 10X",
  "Alliant Reloder TS 11",
  "Alliant Reloder 15",
  "Alliant Reloder TS 15.5",
  "Alliant Reloder 16",
  "Alliant Reloder 17",
  "Alliant Reloder 19",
  "Alliant Reloder 22",
  "Alliant Reloder 23",
  "Alliant Reloder 25",
  "Alliant Reloder 26",
  "Alliant Reloder 33",
  "Alliant Reloder 50",
  // Alliant (pistol/shotgun)
  "Alliant Bullseye",
  "Alliant Red Dot",
  "Alliant Green Dot",
  "Alliant Blue Dot",
  "Alliant Clay Dot",
  "Alliant Herco",
  "Alliant American Select",
  "Alliant Sport Pistol",
  "Alliant Power Pistol",
  "Alliant Power Pro 300-MP",
  "Alliant Unique",
  "Alliant 2400",
  "Alliant BE-86",
  "Alliant e3",
  "Alliant Extra-Lite",
  "Alliant Pro Reach",
  "Alliant Promo",
  "Alliant Steel",

  // Norma
  "Norma 200",
  "Norma 201",
  "Norma 202",
  "Norma 203-B",
  "Norma 204",
  "Norma 217",
  "Norma URP",
  "Norma MRP",

  // Vectan (rifle SP series)
  "Vectan SP2",
  "Vectan SP3",
  "Vectan SP4",
  "Vectan SP5",
  "Vectan SP6",
  "Vectan SP7",
  "Vectan SP8",
  "Vectan SP9",
  "Vectan SP10",
  "Vectan SP11",
  "Vectan SP12",
  "Vectan SP13",
  // Vectan (pistol)
  "Vectan A0",
  "Vectan A1",
  "Vectan AS",
  "Vectan Ba6½",
  "Vectan Ba7½",
  "Vectan Ba9",
  "Vectan Ba9½",
  "Vectan Ba10",
];
